

pub const UNAUTHORIZED: felt252 = 'UNAUTHORIZED';
pub const INVALID_AMOUNT: felt252 = 'INVALID_AMOUNT';
pub const INVALID_LENGTH: felt252 = 'INVALID_LENGTH';
pub const INSUFFICIENT_BALANCE: felt252 = 'INSUFFICIENT_BALANCE';
pub const EMPLOYEE_NOT_FOUND: felt252 = 'EMPLOYEE_NOT_FOUND';
pub const EMPLOYEE_ALREADY_EXIST: felt252 = 'EMPLOYEE_ALREADY_EXIST';
pub const INVALID_ADDRESS: felt252 = 'INVALID_ADDRESS';
pub const EXCEEDS_LIMIT: felt252 = 'EXCEEDS_LIMIT';
pub const MAX_EMPLOYEE: felt252 = 'MAX_EMPLOYEE';
pub const INVALID_TIME: felt252 = 'INVALID_TIME';
pub const ALREADY_INITIALIZED: felt252 = 'ALREADY_INITIALIZED';